services:
  web:
    image: odoo:latest
    container_name: odoo
    user: root
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - AUTH_NET_API_LOGIN_ID=${AUTH_NET_API_LOGIN_ID}
      - AUTH_NET_TRANSACTION_KEY=${AUTH_NET_TRANSACTION_KEY}
    volumes:
      - ./custom_modules:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
      - odoo-sessions:/var/lib/odoo/sessions
    command: bash -c "chown -R odoo:odoo /var/lib/odoo/sessions && chmod -R 700 /var/lib/odoo/sessions && /entrypoint.sh odoo"  # Fix permissions
    networks:
      - odoo-network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Persist certificates
    ports:
      - "80:80"
      - "443:443"
    networks:
      - odoo-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - odoo-network

  frontend:
    build:
      context: ../boltwebapp-frontend # Specify the path to your frontend app
      dockerfile: Dockerfile  # This is optional if your Dockerfile is named 'Dockerfile'
    container_name: boltwebapp-frontend
    environment:
      - NODE_ENV=production
    networks:
      - odoo-network

volumes:
  odoo-data:
  db-data:
  odoo-sessions:

networks:
  odoo-network:
    driver: bridge
