version: '3'

services:
  web:
    build: .
    container_name: odoo
    user: root  # Temporarily run as root to fix permissions
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - AUTH_NET_API_LOGIN_ID=${AUTH_NET_API_LOGIN_ID}
      - AUTH_NET_TRANSACTION_KEY=${AUTH_NET_TRANSACTION_KEY}
    volumes:
      - ./custom_modules:/mnt/extra-addons  # Mount your custom modules directory
      - odoo-data:/var/lib/odoo
      - odoo-sessions:/var/lib/odoo/sessions
    command: bash -c "chown -R odoo:odoo /var/lib/odoo/sessions && chmod -R 700 /var/lib/odoo/sessions && /entrypoint.sh odoo"
    networks:
      - odoo-network

  db:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt # To store SSL certificates
    depends_on:
      - web
    networks:
      - odoo-network

volumes:
  odoo-data:
  db-data:
  odoo-sessions:

networks:
  odoo-network:
    driver: bridge
