services:
  web:
    build: .
    container_name: odoo
    user: root  # Run as root initially to set permissions
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
      - odoo-sessions:/var/lib/odoo/sessions
    command: bash -c "chown -R odoo:odoo /var/lib/odoo/sessions && chmod -R 700 /var/lib/odoo/sessions && /entrypoint.sh odoo"  # Set the correct permissions
    networks:
      - odoo-network

  db:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

volumes:
  odoo-data:
  db-data:
  odoo-sessions:

networks:
  odoo-network:
    driver: bridge
